### ISSUE TITLE
Echange Packs GH Action workflows disabled after 60days of inactivity

### ISSUE THREAD

**Issue by armab** [StackStorm-Exchange/ci#136]
The problem when there were no commits in the repository for `60 days`, - Github Automatically disables CI for it.
It happens all the time when we review new contributions in Exchange and figure out after merging that CI didn't run resulting in post-merge linting errors.

Possible solutions:

1)  https://github.com/marketplace/actions/keepalive-workflow heart beat commits .. :nauseated_face: sounds like a hack
2) Per @nzlosh  There's a REST API endpoint that can be called to enable workflows, so that'd be more robust.  https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#enable-a-workflow  We could schedule an St2 workflow that iterates all exchange repos and calls the API to enable CI workflows. From the possible workarounds, this looks like the cleanest and most maintainable way to workaround the github limitation.

3) Considering the StackStorm instance is automatically started/stopped, 3rd option could be an AWS Lambda function trying to re-enable GH Action Workflows for the Exchange repos. Example solution https://stackoverflow.com/a/68591566/4533625

**Comment by mamercad** [comment]
I mean, I definitely ❤️ StackStorm for running this, but, what about just creating another Workflow that does it?

```yaml
name: keepalive

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:

  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: keepalive
        run: |
          curl \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer ${GITHUB_TOKEN}" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --request PUT \
            --verbose \
            https://api.github.com/repos/OWNER/REPO/actions/workflows/WORKFLOW/enable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I'm sure there's an API endpoint for enumerating all of the repositories in an organization...
